### ISSUE TITLE
About window broken in 0.3.4

### ISSUE THREAD

**Issue by bobvandevijver** [kriskbx/gitlab-time-tracker-taskbar#24]
![image](https://user-images.githubusercontent.com/1835343/44870280-1311c580-ac90-11e8-8b08-e35b67dda050.png)

**Comment by kriskbx** [comment]
I don't know exactly what's going on, but the `about.html` is not included in the packages... I tried renaming `about.html` to something else without the word "about" in it and it suddenly started working again. So: `about2.html` doesn't work but `test.html` does... what the ... 😄 
Will be fixed in the next release.
