### ISSUE TITLE
The list of time entries is empty on new installation

### ISSUE THREAD

**Issue by daften** [kriskbx/gitlab-time-tracker-taskbar#27]
It seems old time entries aren't synced from Gitlab. The project list is synced, and I can select issues, so tracking time works fine. But the list of time entries isn't filled ATM. I tried looking in the package contents, but couldn't find the gtt binary (of the library) to manually trigger a sync to see if that fixed it.

**Comment by kriskbx** [comment]
I'm sorry, there's no sync from GitLab to your local machine. If you want to get reports you should take a look at the CLI. At the moment I'm concentrating all my efforts on the time monitoring part because GitLab itself will implement reports in the future. The whole sync-mechanism and the log window with an overview of your local time records were built to ensure that you can use gtt when you're offline and sync everything to GitLab when you get access to the internet.

**Comment by daften** [comment]
Aah, ok. I'll close this so the issue overview remains clean, feel free to re-open when this is something that would be worthwhile to implement. I already tried the report feature from gtt, and it's awesome, thanks :)
