### ISSUE TITLE
Unable to do any action after Start/Stop.

### ISSUE THREAD

**Issue by RinatGumarov** [kriskbx/gitlab-time-tracker-taskbar#36]
I have to restart gtt everytime I want to press Start/Stop.

**Comment by toxsick** [comment]
me too. had the feeling it worked at the first time though ;( Really want to fix this, because the app would be killer for me!

**Comment by toxsick** [comment]
Can I perhaps start in debug mode somehow to see what is going on?

**Comment by daften** [comment]
Wouldn't it be better to add debug:true to the compile process and release debug binaries instead of enabling debug for everybody? (If it's feasible to do this ofcourse).

**Comment by toxsick** [comment]
Thanks for the update @kriskbx but this still happens for me with version v0.3.9. Can I debug this anyhow?

**Comment by kriskbx** [comment]
If an exception is thrown the application will ask you to send an error report, which is handled by Sentry. So I always know what's going on when a critical error occours. By default the app logs a lot of things. You can access the logs here:

Linux: `~/.config/gtt-taskbar/log.log`
macOS: `~/Library/Logs/gtt-taskbar/log.log`
Windows: `%USERPROFILE%\AppData\Roaming\gtt-taskbar\log.log`

I just pushed version 0.3.10 with some bugfixes. Please download and try again. (Keep in mind that it can take up to 20 minutes for the Continuos Integration Pipeline to build and push binaries to the release page)

**Comment by toxsick** [comment]
Thanks for the info @kriskbx, but also the new version didn't chance anything about it. I already checked out the project and started with `yarn start`, so I already see the logs, but there is no exception thrown and the sentry hook isn't called.

Here is what happens when I start and start timetracking on an issue:

```
yarn run v1.13.0
$ electron-forge start
✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies: 1 / 1
✔ Launching Application
13:33:03.488 › Running on mac
2019-02-01 13:33:03.498 Electron[40805:809556] *** WARNING: Textured window <AtomNSWindow: 0x7fd332036e40> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
13:33:03.592 › Added config watcher
13:33:03.594 › Added frames watcher
13:33:04.195 › Loaded config
13:33:04.199 › Queried status
13:33:04.200 › Queried projects
13:33:04.204 › Queried issues for project fuf/gitlab-time-tracker-taskbar
13:33:04.205 › Queried merge requests for project fuf/gitlab-time-tracker-taskbar
13:33:04.206 › Sync started

# now I press start
13:33:14.925 › Started time monitoring for fuf/gitlab-time-tracker-taskbar issue 2
```

After that all buttons are disabled and nothing happens anymore:

<img width="441" alt="gtt-taskbar 2019-02-01 13-40-26" src="https://user-images.githubusercontent.com/951466/52123622-028ebe00-2627-11e9-9acb-8b910338bedc.png">

So I close the app and start again:

```
$ electron-forge start
✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies: 1 / 1
✔ Launching Application
13:41:28.297 › Running on mac
2019-02-01 13:41:28.307 Electron[40979:816787] *** WARNING: Textured window <AtomNSWindow: 0x7fd46a83dbe0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
13:41:28.396 › Added config watcher
13:41:28.399 › Added frames watcher
13:41:29.065 › Loaded config
13:41:29.069 › Queried status
13:41:29.071 › Queried projects
13:41:29.075 › Queried issues for project fuf/gitlab-time-tracker-taskbar
13:41:29.076 › Queried merge requests for project fuf/gitlab-time-tracker-taskbar
13:41:29.078 › Sync started
```

Now the app looks like this:

<img width="419" alt="gtt-taskbar 2019-02-01 13-42-18" src="https://user-images.githubusercontent.com/951466/52123709-34a02000-2627-11e9-98dd-db77c469b1bb.png">

I hit stop and this happens and it stays like that:

<img width="445" alt="gtt-taskbar 2019-02-01 13-43-23" src="https://user-images.githubusercontent.com/951466/52123779-66b18200-2627-11e9-9049-42a6febecde4.png">

The output is:

```
13:43:08.746 › Stopped time monitoring
13:43:08.766 › Sync started
```

So i guess the sync is hanging somehow?

regards Hannes

**Comment by kriskbx** [comment]
Thanks for investigating. I think the problem is not the sync itself but the file watchers. When you start time monitoring, a new "frame" (that's what I called it) is created. A frame is just a JSON file which contains the project namespace, issue id and the timestamp when you started it. When you stop time monitoring another timestamp is added to the same JSON file. The main process watches the frames folder and the containing files for updates or additions, parses them and updates the interface accordingly. I did it this way, so the taskbar app is compatible with the CLI and you can use both at the same time to start/stop/cancel time monitoring. Your log doesn't show the event that a file was indeed added or updated. I use chokidar under the hood to watch files and folders and I figured it does a great job of abstracting the differences between all the operating systems, but maybe I'm wrong. What OS are you using excatly?

**Comment by toxsick** [comment]
Thanks for the clarification. I use macOS 10.14.2 (Mojave) and the NodeJS v10.15.1

**Comment by kriskbx** [comment]
Sorry, I'm not able to reproduce your problem. Maybe it's a permission thing? Can delete your config folder `~/.local/share/.gtt` (back it up first, though) and try again?

**Comment by toxsick** [comment]
Sorri for the late reply. I tried it a few days ago and it didn't work. Now I try again today and it seems to work :)

The thing is that I use a selfhosted Gitlab instance with self signed cert. My suspicion is that it has to do anything with that. The insecure option does not work for me, so I have to bundle my own version.

But for now it works for me... BIG THANKS!

**Comment by kriskbx** [comment]
The sync has nothing to do with starting or stopping time monitoring. It's an asynchronous process. But I'm glad it works for you now. If you still need help feel free to reopen the issue or create a new one.
